### ISSUE TITLE
ImageClassifierDataset no longer exists?

### ISSUE THREAD

**Issue by Data-drone** [sgugger/Deep-Learning#5]
when I try to fun your notebook I get:

`NameError: name 'ImageClassifierData' is not defined`

what is the cause of this issue?

**Comment by sgugger** [comment]
Are you using fastai v0.7? It's not compatible with fastai v1.

**Comment by gititnaren** [comment]
Though it is an old thread. Can someone respond to this issue. I am facing the same error :: ImageClassifierData is not defined.

I am using fastai v1 kernel on windows 10, Jupyter Notebook.
Appreciate any help on this, Thanks.

**Comment by Data-drone** [comment]
the author said you have to use fastai v0.7?
